server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  zipkin:
      base-url: http://localhost:9411/
      enabled: true
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: serie-service
          uri: lb://serie-service
          predicates:
            - Path=/series/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: seriesService
                fallbackUri: forward:/fallback/series

info:
  app:
    name: ${spring.application.name}
queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway