server:
  port: ${PORT:${SERVER_PORT:0}}

idRandom: ${random.value}

spring:
  zipkin:
      base-url: http://localhost:9411/
      enabled: true
  application:
    name: movie-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq3
    port: 5672

message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
queue:
  movie:
    name: MovieQueue