port: 8010
spring:
  zipkin:
      base-url: http://localhost:9411/
      enabled: true
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: netflix
      port: 27017